# Generated by Django 4.2 on 2023-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='AST',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='BLK',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='DRB',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='ORB',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='PF',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='PTS',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='STL',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='TOV',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='TRB',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='effect_fg_percent',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='field_attempts',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='field_goals',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='field_percent',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='ft',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='ft_percent',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='fta',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='games',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='games_started',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='minutes_pg',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='three_attempts',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='three_fg',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='three_percent',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='two_attempts',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='two_fg',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='two_percent',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
