# Generated by Django 4.2 on 2023-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0002_alter_playerdata_ast_alter_playerdata_blk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='season',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='team',
            field=models.CharField(default='', max_length=30),
        ),
    ]
