# Generated by Django 4.2 on 2023-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0003_playerdata_season_playerdata_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='season',
            field=models.IntegerField(null=True),
        ),
    ]
