# Generated by Django 4.2 on 2023-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0005_alter_playerdata_ast_alter_playerdata_blk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAdvancedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('games', models.IntegerField(null=True)),
                ('minutes_played', models.IntegerField(null=True)),
                ('PER', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('TS_percent', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('three_p_attempt_rate', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ft_attempt_rate', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('orb_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('drb_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('trb_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ast_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('stl_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('blk_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tov_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('usg_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ows', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dws', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ws', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ws_per_48', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('obpm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dbpm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bpm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vorp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTotalsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('games', models.IntegerField(null=True)),
                ('games_started', models.IntegerField(null=True)),
                ('minutes_played', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('field_goals', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('field_attempts', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('field_percent', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('three_fg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('three_attempts', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('three_percent', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('two_fg', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('two_attempts', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('two_percent', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('effect_fg_percent', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ft', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fta', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ft_percent', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ORB', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('DRB', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('TRB', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('AST', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('STL', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('BLK', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('TOV', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PF', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PTS', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
            ],
        ),
    ]
