# Generated by Django 4.2 on 2023-04-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0006_playeradvanceddata_playertotalsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertotalsdata',
            name='AST',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='BLK',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='DRB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='ORB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='PF',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='PTS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='STL',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='TOV',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='TRB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='effect_fg_percent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='field_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='field_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='field_percent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='ft_percent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='fta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='minutes_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='three_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='three_fg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='three_percent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='two_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='two_fg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playertotalsdata',
            name='two_percent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
