# Generated by Django 4.2 on 2023-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0008_playerplayofftotalsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPlayoffAdvancedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('games', models.IntegerField(null=True)),
                ('minutes_played', models.IntegerField(null=True)),
                ('PER', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('TS_percent', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('three_p_attempt_rate', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('ft_attempt_rate', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('orb_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('drb_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('trb_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ast_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('stl_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('blk_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tov_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('usg_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ows', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dws', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ws', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ws_per_48', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('obpm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dbpm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bpm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vorp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
            ],
        ),
    ]
