# Generated by Django 4.2 on 2023-05-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0009_playerplayoffadvanceddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeradvanceddata',
            name='PER',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='playerplayoffadvanceddata',
            name='PER',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
