# Generated by Django 4.2 on 2023-05-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0011_alter_playerplayoffadvanceddata_bpm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255, null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
    ]
