# Generated by Django 4.2 on 2023-05-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0012_playersalarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersalarydata',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playersalarydata',
            name='team',
            field=models.CharField(default='', max_length=30),
        ),
    ]
