# Generated by Django 4.2 on 2023-05-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0013_playersalarydata_season_playersalarydata_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerShotChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=255)),
                ('top', models.IntegerField(null=True)),
                ('left', models.IntegerField(null=True)),
                ('date', models.CharField(default='', max_length=255)),
                ('qtr', models.CharField(default='', max_length=6)),
                ('time_remaining', models.IntegerField(null=True)),
                ('result', models.BooleanField(null=True)),
                ('shot_type', models.CharField(default='', max_length=6)),
                ('distance_ft', models.IntegerField(null=True)),
                ('lead', models.BooleanField(null=True)),
                ('lebron_team_score', models.IntegerField(null=True)),
                ('opponent_team_score', models.IntegerField(null=True)),
                ('opponent', models.CharField(default='', max_length=30)),
                ('team', models.CharField(default='', max_length=30)),
                ('season', models.IntegerField(null=True)),
            ],
        ),
    ]
