# Generated by Django 4.2 on 2023-05-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0014_playershotchartdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playershotchartdata',
            name='time_remaining',
            field=models.CharField(default='', max_length=12),
        ),
    ]
