# Generated by Django 4.2 on 2023-05-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0015_alter_playershotchartdata_time_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playershotchartdata',
            name='qtr',
            field=models.CharField(default='', max_length=255),
        ),
    ]
