# Generated by Django 4.2 on 2023-09-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0017_alter_playershotchartdata_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeradvanceddata',
            name='ft_attempt_rate',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
